/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_STEGANOGRAPHY2_H
#define PHP_STEGANOGRAPHY2_H

extern zend_module_entry steganography2_module_entry;
#define phpext_steganography2_ptr &steganography2_module_entry

#ifdef PHP_WIN32
# define PHP_STEGANOGRAPHY2_API __declspec(dllexport)
#else
# define PHP_STEGANOGRAPHY2_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(steganography2);
PHP_MSHUTDOWN_FUNCTION(steganography2);
PHP_RINIT_FUNCTION(steganography2);
PHP_RSHUTDOWN_FUNCTION(steganography2);
PHP_MINFO_FUNCTION(steganography2);

ZEND_NAMED_FUNCTION(_wrap_steg_easy_apply2);
ZEND_NAMED_FUNCTION(_wrap_steg_easy_decode2);
#endif /* PHP_STEGANOGRAPHY2_H */
