<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('steganography2')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_steganography2.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('steganography2.so')) return;
    } else {
      if (!dl('steganography2.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class steganography2 {
	static function steg_easy_apply2($message,$watermark_font_size,$Steg_Encode_Old_Overlay_On,$Y_BUMP,$Y_BUMP_REACTIVE,$Watermark_X_Step,$Watermark_Y_Step,$Steg_Encode_Anti_Crop_On,$Steg_Anti_Crop_Percent,$Steg_Encode_Col_Chroma_Shift_On,$Steg_Encode_Col_Chroma_Shift,$Steg_Encode_Col_Chroma_Shift_Cb_On,$Steg_Encode_Col_Chroma_Shift_Cr_On,$Steg_Encode_Col_Chroma_Shift_Down,$Steg_Encode_Col_Step_factor,$Cb_Shift,$Cr_Shift,$Steg_Encode_Message,$infile,$outfile) {
		return steg_easy_apply2($message,$watermark_font_size,$Steg_Encode_Old_Overlay_On,$Y_BUMP,$Y_BUMP_REACTIVE,$Watermark_X_Step,$Watermark_Y_Step,$Steg_Encode_Anti_Crop_On,$Steg_Anti_Crop_Percent,$Steg_Encode_Col_Chroma_Shift_On,$Steg_Encode_Col_Chroma_Shift,$Steg_Encode_Col_Chroma_Shift_Cb_On,$Steg_Encode_Col_Chroma_Shift_Cr_On,$Steg_Encode_Col_Chroma_Shift_Down,$Steg_Encode_Col_Step_factor,$Cb_Shift,$Cr_Shift,$Steg_Encode_Message,$infile,$outfile);
	}

	static function steg_easy_decode2($message,$Steg_Decode_Specific_Diff,$Cb_Shift,$Cr_Shift,$Steg_Decode_Bound,$Steg_Decode_Anti_Crop_On,$Steg_Decode_No_Crop_Hint,$Steg_Anti_Crop_Percent,$Steg_Decode_Ignore_Y,$Steg_Decode_Y_Bound,$infile,$outfile) {
		return steg_easy_decode2($message,$Steg_Decode_Specific_Diff,$Cb_Shift,$Cr_Shift,$Steg_Decode_Bound,$Steg_Decode_Anti_Crop_On,$Steg_Decode_No_Crop_Hint,$Steg_Anti_Crop_Percent,$Steg_Decode_Ignore_Y,$Steg_Decode_Y_Bound,$infile,$outfile);
	}
}

/* PHP Proxy Classes */

?>
